---
Style/Documentation:
  Enabled: false

Style/FileName:
  Enabled: false

Style/IndentHeredoc:
  Enabled: false

MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Enabled: false
# EOF
